import S from '@sanity/desk-tool/structure-builder'
import {
  MdSettings,
  MdHome,
  MdDashboard,
  MdLibraryBooks,
  MdPalette,
  MdMoreHoriz,
  MdFolderOpen,
  MdLocationOn,
  MdPeople,
  MdPerson,
  MdVpnKey,
} from 'react-icons/md'

export default () =>
  S.list()
    .title('Site')
    .items([
      S.listItem()
        .title('Configuration')
        .icon(MdSettings)
        .child(
          S.editor()
            .id('config')
            .schemaType('config')
            .documentId('global-config'),
        ),
      S.listItem()
        .title('Pages')
        .icon(MdLibraryBooks)
        .child(
          S.list()
            .title('Pages')
            .items([
              S.listItem()
                .title('Home')
                .icon(MdHome)
                .child(
                  S.editor()
                    .id('home')
                    .schemaType('home')
                    .documentId('homepage'),
                ),
              S.listItem()
                .title('Project Index')
                .icon(MdDashboard)
                .child(
                  S.editor()
                    .id('projects')
                    .schemaType('projects')
                    .documentId('projectspage'),
                ),
              S.listItem()
                .title('People Index')
                .icon(MdPeople)
                .child(
                  S.editor()
                    .id('people')
                    .schemaType('people')
                    .documentId('peoplepage'),
                ),
              S.listItem()
                .title('Opportunity Index')
                .icon(MdVpnKey)
                .child(
                  S.editor()
                    .id('opportunities')
                    .schemaType('opportunities')
                    .documentId('opportunitiespage'),
                ),
            ]),
        ),
      S.listItem()
        .title('Projects')
        .icon(MdPalette)
        .child(
          S.list()
            .title('Projects')
            .items([
              S.listItem()
                .title('All Projects')
                .icon(MdMoreHoriz)
                .child(S.documentTypeList('project')),
              S.listItem()
                .title('Categories')
                .icon(MdFolderOpen)
                .child(S.documentTypeList('category')),
              S.listItem()
                .title('Locations')
                .icon(MdLocationOn)
                .child(S.documentTypeList('location')),
            ]),
        ),
      S.listItem()
        .title('People')
        .icon(MdPerson)
        .child(S.documentTypeList('person')),
    ])
